 'use strict';   
import {calc} from './calc';
import {Form} from './form';
import {tabs} from './tabs';
import {slider} from './slider';
import {timer} from './timer';
import {modal} from './modal';
calc();
Form();
tabs();
slider();
timer();
modal();
